package com.hibb.dm;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;

@Entity 
public class Course {
	
	@Id // id will be the primary key of this entity
	@GeneratedValue   // this value will be generated by JPA (ie hibernate will create a sequence on the table and use it to generate this record) 
	private Long id;
	
	private String name;
	
	private String faculty;
	
	private int duration;

	@OneToOne(mappedBy = "course")
	@JoinColumn(name = "student_id", nullable = true)
	private Student student;
	
	public Course() {
		
	}
	
	public Course(String name, String faculty, int duration) {
		super();
		this.name = name;
		this.faculty = faculty;
		this.duration = duration;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFaculty() {
		return faculty;
	}

	public void setFaculty(String faculty) {
		this.faculty = faculty;
	}

	public int getDuration() {
		return duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}
	
}
