package com.hibb.dm;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;


@Entity // ie this class is a JPA entity
public class Student implements Serializable {

	@Id // id will be the primary key of this entity
	@GeneratedValue   // this value will be generated by JPA (ie hibernate will create a sequence on the table and use it to generate this record) 
	private Long id;
		
	private String name;
	
	private String passportNumber;
	
	@ManyToMany  
	private List<CollegeComputer> collegeComputers;
	
	@ElementCollection
    @JoinTable(
        name="student_tel_nums",  // the new table name
        joinColumns = @JoinColumn( name="student_id") // the link to students
      )
    @Column(name="telNums") // the link to telephone numbers
	private List<String> telNumbers;
	
	@OneToMany
	private Set<Cat> catSet;
	
	@OneToOne
	private Course course;
	
	@Convert(converter = GenderConverter.class)
	private Gender gender = Gender.MALE;
	
	
//	@Column
	private LocalDate birthday;
	
//	@Column
	private LocalDateTime magicMoment;
		
	
	public Student() {  // default constructor is necessary for JPA
		
	}

	public Student(Long id, String name, String passportNumber) {
		super();
		this.id = id;
		this.name = name;
		this.passportNumber = passportNumber;
	}

	public Student(String name, String passportNumber) {
		super();
		this.name = name;
		this.passportNumber = passportNumber;
	}
	
	
	public Student(String name, String passportNumber, List<CollegeComputer> collegeComputers) {
		super();
		this.name = name;
		this.passportNumber = passportNumber;
		this.collegeComputers = collegeComputers;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassportNumber() {
		return passportNumber;
	}

	public void setPassportNumber(String passportNumber) {
		this.passportNumber = passportNumber;
	}
	
	public List<CollegeComputer> getCollegeComputers() {
		return collegeComputers;
	}

	public void setCollegeComputers(List<CollegeComputer> collegeComputers) {
		this.collegeComputers = collegeComputers;
	}
	
	public Set<Cat> getCatSet() {
		return catSet;
	}

	public void setCatSet(Set<Cat> catSet) {
		this.catSet = catSet;
	}

	public List<String> getTelNumbers() {
		return telNumbers;
	}

	public void setTelNumbers(List<String> telNumbers) {
		this.telNumbers = telNumbers;
	}

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Gender getGender() {
		return gender;
	}

	public void setGender(Gender gender) {
		this.gender = gender;
	}

	public LocalDate getBirthday() {
		return birthday;
	}

	public void setBirthday(LocalDate birthday) {
		this.birthday = birthday;
	}

	public LocalDateTime getMagicMoment() {
		return magicMoment;
	}

	public void setMagicMoment(LocalDateTime magicMoment) {
		this.magicMoment = magicMoment;
	}
	
	
	
}